### ISSUE TITLE
こんにちは、早速アライメントのコードを試しに実行してみました。

### ISSUE THREAD

**Issue by yuuSiVo** [dhgrs/chainer-phoneme-alignment#1]
こんにちは。試しにアライメントのtrain.pyを実行してみましたが、下記のエラーが出ます

Exception in main training loop: division by zero
Traceback (most recent call last):
  File "C:\Users\K017C1149\AppData\Local\Programs\Python\Python36-32\lib\site-packages\chainer\training\trainer.py", line 296, in run
    while not stop_trigger(self):
  File "C:\Users\K017C1149\AppData\Local\Programs\Python\Python36-32\lib\site-packages\chainer\training\triggers\interval_trigger.py", line 51, in __call__
    epoch_detail = updater.epoch_detail
  File "C:\Users\K017C1149\AppData\Local\Programs\Python\Python36-32\lib\site-packages\chainer\training\updater.py", line 159, in epoch_detail
    return self._iterators['main'].epoch_detail
  File "C:\Users\K017C1149\AppData\Local\Programs\Python\Python36-32\lib\site-packages\chainer\iterators\serial_iterator.py", line 86, in epoch_detail
    return self.epoch + self.current_position / len(self.dataset)
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "train.py", line 45, in <module>
    trainer.run()
  File "C:\Users\K017C1149\AppData\Local\Programs\Python\Python36-32\lib\site-packages\chainer\training\trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "C:\Users\K017C1149\AppData\Local\Programs\Python\Python36-32\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\K017C1149\AppData\Local\Programs\Python\Python36-32\lib\site-packages\chainer\training\trainer.py", line 296, in run
    while not stop_trigger(self):
  File "C:\Users\K017C1149\AppData\Local\Programs\Python\Python36-32\lib\site-packages\chainer\training\triggers\interval_trigger.py", line 51, in __call__
    epoch_detail = updater.epoch_detail
  File "C:\Users\K017C1149\AppData\Local\Programs\Python\Python36-32\lib\site-packages\chainer\training\updater.py", line 159, in epoch_detail
    return self._iterators['main'].epoch_detail
  File "C:\Users\K017C1149\AppData\Local\Programs\Python\Python36-32\lib\site-packages\chainer\iterators\serial_iterator.py", line 86, in epoch_detail
    return self.epoch + self.current_position / len(self.dataset)
ZeroDivisionError: division by zero

balance_sentences.txtとWavは配置してあります。

**Comment by dhgrs** [comment]
環境による差をなくすために、Google Colaboratory上で動かせるノートブックを用意しました。現状の最新コミット 5d5addeb7db2c24c146342c0e18362b6d7ff9d0d から試してみてください。上のセルから順に実行していくだけで使えます。
まとまった時間が取れた際にREADMEを作って実行環境を簡単にまとめますので、その環境で試しても同様あるいは別のバグが出るようでしたら、修正を試みます。もう少しお待ちください。
